-- MySQL Script generated by MySQL Workbench
-- 04/13/16 01:02:00
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `iduser` VARCHAR(200) NOT NULL,
  `nome` VARCHAR(200) NOT NULL,
  `datanasc` DATE NOT NULL,
  `cidade` VARCHAR(200) NOT NULL,
  `estado` VARCHAR(2) NOT NULL,
  `instituicao` VARCHAR(200) NOT NULL DEFAULT 'nenhuma',
  `cep` VARCHAR(10) NOT NULL,
  `email` VARCHAR(200) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`iduser`),
  UNIQUE INDEX `iduser_UNIQUE` (`iduser` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`codes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`codes` (
  `idcode` INT ZEROFILL NOT NULL,
  `codigo` VARCHAR(45) NOT NULL,
  `adm` INT ZEROFILL NOT NULL,
  PRIMARY KEY (`idcode`),
  UNIQUE INDEX `idcode_UNIQUE` (`idcode` ASC),
  UNIQUE INDEX `code_UNIQUE` (`codigo` ASC),
  UNIQUE INDEX `adm_UNIQUE` (`adm` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`professor` (
  `iduser` VARCHAR(100) NOT NULL,
  `idcode` INT NOT NULL,
  PRIMARY KEY (`iduser`, `idcode`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`assunto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`assunto` (
  `idassunto` INT NOT NULL AUTO_INCREMENT,
  `nomeassunto` VARCHAR(200) NOT NULL,
  `iduser` VARCHAR(100) NOT NULL,
  `idcode` INT NOT NULL,
  PRIMARY KEY (`idassunto`),
  UNIQUE INDEX `idassunto_UNIQUE` (`idassunto` ASC),
  INDEX `FKprofessor.assunto_idx` (`iduser` ASC, `idcode` ASC),
  CONSTRAINT `FKprofessor.assunto`
    FOREIGN KEY (`iduser` , `idcode`)
    REFERENCES `mydb`.`professor` (`iduser` , `idcode`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`modulo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`modulo` (
  `idmodulo` INT NOT NULL AUTO_INCREMENT,
  `nomemodulo` VARCHAR(250) NOT NULL,
  `idassunto` INT NOT NULL,
  PRIMARY KEY (`idmodulo`),
  UNIQUE INDEX `idmodulo_UNIQUE` (`idmodulo` ASC),
  INDEX `pkassunto.modulo_idx` (`idassunto` ASC),
  CONSTRAINT `fkassunto.modulo`
    FOREIGN KEY (`idassunto`)
    REFERENCES `mydb`.`assunto` (`idassunto`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`resposta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`resposta` (
  `idresposta` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  `conteudoresposta` MEDIUMBLOB NOT NULL,
  PRIMARY KEY (`idresposta`),
  UNIQUE INDEX `idresposta_UNIQUE` (`idresposta` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`item` (
  `iditem` INT NOT NULL AUTO_INCREMENT,
  `nomeitem` VARCHAR(250) NOT NULL,
  `conteudoitem` MEDIUMBLOB NOT NULL,
  `idmodulo` INT NOT NULL,
  PRIMARY KEY (`iditem`),
  UNIQUE INDEX `iditem_UNIQUE` (`iditem` ASC),
  INDEX `fkmodulo.item_idx` (`idmodulo` ASC),
  CONSTRAINT `fkmodulo.item`
    FOREIGN KEY (`idmodulo`)
    REFERENCES `mydb`.`modulo` (`idmodulo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`questao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`questao` (
  `idquestao` INT NOT NULL AUTO_INCREMENT,
  `nomequestao` VARCHAR(250) NOT NULL,
  `iditem` INT NOT NULL,
  PRIMARY KEY (`idquestao`),
  UNIQUE INDEX `idquestao_UNIQUE` (`idquestao` ASC),
  INDEX `fkitem.questao_idx` (`iditem` ASC),
  CONSTRAINT `fkitem.questao`
    FOREIGN KEY (`iditem`)
    REFERENCES `mydb`.`item` (`iditem`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`dica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`dica` (
  `iddica` INT NOT NULL AUTO_INCREMENT,
  `idquestao` INT NOT NULL,
  `conteudodica` BLOB NOT NULL,
  PRIMARY KEY (`iddica`),
  UNIQUE INDEX `iddica_UNIQUE` (`iddica` ASC),
  INDEX `fkquestao.dica_idx` (`idquestao` ASC),
  CONSTRAINT `fkquestao.dica`
    FOREIGN KEY (`idquestao`)
    REFERENCES `mydb`.`questao` (`idquestao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`questaoresposta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`questaoresposta` (
  `idquestao` INT NOT NULL,
  `idresposta` INT NOT NULL,
  `tipo` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`idquestao`, `idresposta`),
  INDEX `fkresposta.questaoresposta_idx` (`idresposta` ASC),
  CONSTRAINT `fkquestao.questaoresposta`
    FOREIGN KEY (`idquestao`)
    REFERENCES `mydb`.`questao` (`idquestao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fkresposta.questaoresposta`
    FOREIGN KEY (`idresposta`)
    REFERENCES `mydb`.`resposta` (`idresposta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`matricula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`matricula` (
  `iduser` VARCHAR(200) NOT NULL,
  `idassunto` INT NOT NULL,
  PRIMARY KEY (`iduser`, `idassunto`),
  INDEX `fkassunto.matricula_idx` (`idassunto` ASC),
  CONSTRAINT `fkuser.matricula`
    FOREIGN KEY (`iduser`)
    REFERENCES `mydb`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fkassunto.matricula`
    FOREIGN KEY (`idassunto`)
    REFERENCES `mydb`.`assunto` (`idassunto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`status` (
  `idstatus` INT NOT NULL,
  `iduser` VARCHAR(200) NOT NULL,
  `idassunto` INT NOT NULL,
  `iditem` INT NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idstatus`),
  INDEX `pkmatricula.status_idx` (`iduser` ASC, `idassunto` ASC),
  INDEX `pkitem.status_idx` (`iditem` ASC),
  CONSTRAINT `pkmatricula.status`
    FOREIGN KEY (`iduser` , `idassunto`)
    REFERENCES `mydb`.`matricula` (`iduser` , `idassunto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `pkitem.status`
    FOREIGN KEY (`iditem`)
    REFERENCES `mydb`.`item` (`iditem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`log` (
  `idlog` INT NOT NULL AUTO_INCREMENT,
  `iduse` VARCHAR(200) NOT NULL,
  `isassunto` INT NOT NULL,
  `idquestao` INT NOT NULL,
  `idresposta` INT NOT NULL,
  PRIMARY KEY (`idlog`),
  UNIQUE INDEX `idlog_UNIQUE` (`idlog` ASC),
  INDEX `fkmatricula.log_idx` (`iduse` ASC, `isassunto` ASC),
  INDEX `fkquestao.log_idx` (`idquestao` ASC, `idresposta` ASC),
  CONSTRAINT `fkmatricula.log`
    FOREIGN KEY (`iduse` , `isassunto`)
    REFERENCES `mydb`.`matricula` (`iduser` , `idassunto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fkquestao.log`
    FOREIGN KEY (`idquestao` , `idresposta`)
    REFERENCES `mydb`.`questaoresposta` (`idquestao` , `idresposta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
